### ISSUE TITLE
Can't use with non-expo project

### ISSUE THREAD

**Issue by flybayer** [expo/expo-gl#2]
I'm trying to use this in a non-expo project but the build is having tons of errors finding files and headers files.

For testing, I've created a brand new react-native app and installed expo-gl exactly as described in the readme (without Cocoapods).

https://github.com/flybayer/TestExpoGL

The build is failing with these errors:
<img width="867" alt="screen shot 2018-09-23 at 16 21 31" src="https://user-images.githubusercontent.com/8813276/45932644-378a5600-bf4d-11e8-90f6-cc7141ffa5ae.png">

I fixed the references to those files but then it couldn't find the EXGL header files. I fixed those references and then it couldn't find the EXGL-CPP header files.

Am I doing something wrong?

@tsapeta this is blocking me on a client project, so I'm happy to pay you for some pairing time or something to get me moving forward.

Thanks!

**Comment by tsapeta** [comment]
Hi @flybayer!
I apologize for these problems you're having 🙁 Could you try with Cocoapods? This way was more thoroughly tested and is probably more common. 

After quick investigation, it seems like the way to install libs without Cocoapods is just not good and we will probably drop it. The xcodeproj file is not being updated when we're changing something in the library, I assume it's because we're developing these libs inside another project (for Expo Client). So this file has a state from the moment when the lib was created 😐

**Comment by flybayer** [comment]
@tsapeta thanks for the quick response! I decided to try Cocoapods even before you suggested, as I decided that's probably what you all were testing with. 

I got much further, but the build is failing with the below error. The code for this is on the `pods` branch of my test repo.

<img width="891" alt="screen shot 2018-09-23 at 17 31 14" src="https://user-images.githubusercontent.com/8813276/45933228-9f916a00-bf56-11e8-8839-abd8497510ee.png">

Also to get that far, I had to add more lines to the Podfile than the readme stated.
```
target 'TestExpoGL' do
  pod 'EXCore', path: '../node_modules/expo-core/ios'
  pod 'EXFileSystemInterface', path: '../node_modules/expo-file-system-interface/ios'
  pod 'EXCameraInterface', path: '../node_modules/expo-camera-interface/ios'
  pod 'EXGL', path: '../node_modules/expo-gl/ios'
  pod 'EXGL-CPP', path: '../node_modules/expo-gl-cpp/cpp'
end

```

**Comment by flybayer** [comment]
For a real device, I get the same error but for the arm64 architecture.

Do I also need to install `expo-react-native-adapter` or anything else?

**Comment by tsapeta** [comment]
Yeah, I completely forgot about RN adapter. So you need to add these two things to your Podfile
```
pod 'EXReactNativeAdapter', path: '../node_modules/expo-react-native-adapter/ios'
pod 'EXFontInterface', path: '../node_modules/expo-font-interface/ios'
```
and ofc install them by yarn or npm.

Unfortunately, I'm still getting some errors. Also, EXReactNativeAdapter automatically installs `React` pod if you don't specify `React` pod in your `Podfile` so I actually have two copies of `React` in the project 😞

**Comment by tsapeta** [comment]
There is also a doc here: https://github.com/expo/expo-react-native-adapter/blob/master/README.md
that should help in making your RN project work with Expo universal modules. But it might not be enough since the use of these modules in vanilla RN apps is still in testing & documenting phase.
Sorry again for these inconveniences! I'll come back to you later, I need to take some sleep (timezone differences 🤦‍♂️).

**Comment by tsapeta** [comment]
I've created a blank new project and setup it in order to make it working with Expo Universal Modules. See [react-native-with-expo-modules](https://github.com/tsapeta/react-native-with-expo-modules).
It contains a correct Podfile that installs `React` and its dependencies through Cocoapods + `EXCore`, `EXReactNativeAdapter` and some interfaces. You just need to add these
```
pod 'EXFileSystemInterface', path: '../node_modules/expo-file-system-interface/ios'
pod 'EXCameraInterface', path: '../node_modules/expo-camera-interface/ios'
pod 'EXGL', path: '../node_modules/expo-gl/ios'
pod 'EXGL-CPP', path: '../node_modules/expo-gl-cpp/cpp'
```

I've setup this project only for iOS 😛 Let me know if you also need any help with Android 🙂

**Comment by flybayer** [comment]
Yay, iOS is working with expo-gl!!

Android is close, but I'm stuck.

1. I tried just adding core to Android on your repo, but it's failing. See  https://github.com/tsapeta/react-native-with-expo-modules/pull/1
2. I successfully added core to my [TestExpoGL repo](https://github.com/flybayer/TestExpoGL), but with expo-gl, the build is failing with the below error. (this code is on the master branch)

```
> Configure project :expo-gl-cpp
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/b/c/TestExpoGL/node_modules/expo-gl-cpp/android/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':expo-gl-cpp'.
> Cannot get property 'absolutePath' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by tsapeta** [comment]
hmm, do you have Android NDK installed? looks like it can't get an absolute path to NDK directory 🤔

**Comment by flybayer** [comment]
No, I didn't realize what it was! Another documentation item. I installed it.

Now my TestExpoGL android app is compiling, but I added an empty GLView and get this runtime error 🤔 This is on the master branch.

<img width="653" alt="screen shot 2018-09-24 at 12 46 51" src="https://user-images.githubusercontent.com/8813276/45966116-424df500-bff8-11e8-99dd-5f41bf78b29f.png">

**Comment by tsapeta** [comment]
Actually I'd like NDK not to be required in case you're just using `expo-gl-cpp` - it should be required only when building from sources. So it's a small bug, thanks for finding that 🙂

So I quickly checked your code in Android folder and seems that you didn't put `new GLPackage()` to module registry. You should add this package here: https://github.com/flybayer/TestExpoGL/blob/6ebdf1bfd34175a3e94ffd948f21bf2761ffb860/android/app/src/main/java/com/testexpogl/MainApplication.java#L52

**Comment by tsapeta** [comment]
^ it's described here: https://github.com/expo/expo-react-native-adapter/blob/master/README.md#android-1

**Comment by flybayer** [comment]
Ok, I figured out the import `import expo.modules.gl.GLPackage;`, but now I get a different runtime error. Updated code on master branch.

<img width="901" alt="screen shot 2018-09-24 at 15 31 15" src="https://user-images.githubusercontent.com/8813276/45974360-1f7b0b00-c00f-11e8-8231-283c52edb4f3.png">

**Comment by flybayer** [comment]
I looks like the adapter readme is missing this part. I got past that error by adding
```
import expo.adapters.react.ReactModuleRegistryProvider;
```
and changing
```diff
-- private final ModuleRegistryProvider mModuleRegistryProvider = new ModuleRegistryProvider(Arrays.<Package>asList(
++ private final ModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(Arrays.<Package>asList(
```

Now it compiles and runs but immediately crashes. Looking into this..

**Comment by tsapeta** [comment]
Damn, this crash log says nothing 😄 Looks like https://github.com/flybayer/TestExpoGL/blob/f2041a01db033d1c1b4c0209d91182e5683cedb3/android/app/build.gradle#L140 doesn't contain all required interfaces - what about `expo-font-interface` and `expo-image-loader-interface` and `expo-permissions-interface`?

**Comment by flybayer** [comment]
Oh yeah, fixed. But still get the same silent crash.

Do I need to add more packages to the registry provider like in this file?
https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/modules/NCL/android/app/src/main/java/io/expo/ncl/MainApplication.java#L22

I tried adding `import expo.modules.permissions.PermissionsPackage;` but the compiler can't find that package.

**Comment by tsapeta** [comment]
It cannot find `expo.modules.permissions.PermissionsPackage` because it sits in `expo-permissions` module 🙂 Probably you don't need to add more packages - then you would have to install `expo-permissions` as well. Generally, the idea is that if you don't use methods that require permissions functionality then you don't have to install interface implementations.

Maybe you can find something more in the logs? Is there a stacktrace? What device or simulator are you using to test?

**Comment by flybayer** [comment]
Ok, I got the actual crash log:
```
09-25 11:57:29.594 22163 22188 I ReactNativeJS: Running application "TestExpoGL" with appParams: {"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
09-25 11:57:29.647 22163 22199 D         : HostConnection::get() New Host Connection established 0xea3b3280, tid 22199
09-25 11:57:29.647 22163 22188 E AndroidRuntime: FATAL EXCEPTION: mqt_js
09-25 11:57:29.647 22163 22188 E AndroidRuntime: Process: com.testexpogl, PID: 22163
09-25 11:57:29.647 22163 22188 E AndroidRuntime: java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/com.testexpogl-1/base.apk)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at expo.modules.gl.cpp.EXGL.<clinit>(EXGL.java:8)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at expo.modules.gl.GLContext$1.run(GLContext.java:91)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
09-25 11:57:29.647 22163 22188 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
09-25 11:57:29.648 19871 20429 W ActivityManager:   Force finishing activity com.testexpogl/.MainActivity
```

**Comment by flybayer** [comment]
Maybe related to how Expo is using SoLoader? Others have had similiar issues: https://github.com/facebook/SoLoader/issues/13

**Comment by flybayer** [comment]
Found the problem!

Fix:
```diff
--implementation 'com.facebook.soloader:soloader:0.1.0'
++implementation 'com.facebook.soloader:soloader:0.5.1'
```
at https://github.com/expo/expo-gl-cpp/blob/master/android/build.gradle#L205

Not sure what the best fix is though.

**Comment by tsapeta** [comment]
Really, this solved the crash? Nice, thanks for this finding! I'm now curious why `soloader:0.1.0` does work in Expo and doesn't work for you 🤔 I'll fix this soon anyway, just need to test a few things after this change 😄

**Comment by Keyj1n** [comment]
With @flybayer repository https://github.com/flybayer/TestExpoGL i get the following error on android

`10-06 14:52:40.855  4358  4358 E AndroidRuntime: Process: com.testexpogl, PID: 4358
10-06 14:52:40.855  4358  4358 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 19 could not be found
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:311)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:618)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-06 14:52:40.855  4358  4358 E AndroidRuntime: Caused by: com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 19 could not be found
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.NativeViewHierarchyManager.resolveViewManager(NativeViewHierarchyManager.java:107)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:357)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:227)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:894)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1001)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:46)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1061)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
10-06 14:52:40.855  4358  4358 E AndroidRuntime:        ... 13 more`

any ideas?

**Comment by ide** [comment]
We'll need to bump the soloader version in Gradle to 0.5.1 exactly (do not use semver, as the Expo client needs that version exactly). On Expo's side we can support both soloader 0.1.0 and 0.5.1 in the Expo runtime and for non-Expo runtimes we can support soloader 0.5.1.
