### ISSUE TITLE
App crashed on builded APK

### ISSUE THREAD

**Issue by Chrisigrimm** [expo/expo-gl#4]
When I start the app and GLView is about to load the app crashed with the following errors

```
10-13 19:34:52.575 18214 18214 I chromium: [INFO:aw_field_trial_creator.cc(54)] First-WebView-Experiment not found
10-13 19:34:52.729 18118 18139 D SoLoader: About to load: libexpo-gl.so
10-13 19:34:52.732 18256 18256 I cr_ChildProcessService: Creating new ChildProcessService pid=18256
10-13 19:34:52.734 18118 18139 D SoLoader: libexpo-gl.so not found on /data/data/de.elumion.lacucaracha6/lib-main
10-13 19:34:52.734 18118 18139 D SoLoader: libexpo-gl.so found on /data/app/de.elumion.lacucaracha6-IuPMq-XPhxP1NP1om41aMg==/lib/arm
10-13 19:34:52.734 18118 18139 D SoLoader: Not resolving dependencies for libexpo-gl.so
10-13 19:34:52.770   960  2810 I ActivityManager: Killing 17739:com.android.chrome:webview_service/u0a56 (adj 906): empty #17
10-13 19:34:52.770   960  2810 I ActivityManager: Killing 16916:com.facebook.katana/u0a110 (adj 906): empty #18
10-13 19:34:52.770   960  1015 W libprocessgroup: kill(-17739, 9) failed: No such process
10-13 19:34:52.793   628   628 I Zygote  : Process 17739 exited due to signal (9)
10-13 19:34:52.801   960  1015 W libprocessgroup: kill(-17739, 9) failed: No such process
10-13 19:34:52.801   960  1015 I libprocessgroup: Successfully killed process cgroup uid 10056 pid 17739 in 30ms
10-13 19:34:52.802   960  1015 W libprocessgroup: kill(-16916, 9) failed: No such process
10-13 19:34:52.810 18118 18139 D SoLoader: Loaded: libexpo-gl.so
10-13 19:34:52.845   960  1015 W libprocessgroup: kill(-16916, 9) failed: No such process
10-13 19:34:52.961   960  1015 I chatty  : uid=1000(system) ActivityManager identical 4 lines
10-13 19:34:53.009   960  1015 W libprocessgroup: kill(-16916, 9) failed: No such process
10-13 19:34:53.026 18118 18139 I ReactNativeJS: []
10-13 19:34:53.055   960  1015 W libprocessgroup: kill(-16916, 9) failed: No such process
10-13 19:34:53.100   960  1015 W libprocessgroup: kill(-16916, 9) failed: No such process
10-13 19:34:53.111 18118 18139 E ReactNativeJS: Unexpected token ';'. Expected a parameter pattern or a ')' in parameter list.
10-13 19:34:53.119 18118 18140 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-13 19:34:53.119 18118 18140 E AndroidRuntime: Process: de.elumion.lacucaracha6, PID: 18118
10-13 19:34:53.119 18118 18140 E AndroidRuntime: com.facebook.react.common.JavascriptException: Unexpected token ';'. Expected a parameter pattern or a ')' in parameter list., stack:
10-13 19:34:53.119 18118 18140 E AndroidRuntime: compile@684:61342
10-13 19:34:53.119 18118 18140 E AndroidRuntime: vi@684:100038
10-13 19:34:53.119 18118 18140 E AndroidRuntime: <unknown>@684:102446
10-13 19:34:53.119 18118 18140 E AndroidRuntime: _handleContextCreate@641:985
10-13 19:34:53.119 18118 18140 E AndroidRuntime: _onSurfaceCreate@675:852
10-13 19:34:53.119 18118 18140 E AndroidRuntime: g@66:551
10-13 19:34:53.119 18118 18140 E AndroidRuntime: S@66:694
10-13 19:34:53.119 18118 18140 E AndroidRuntime: P@66:748
10-13 19:34:53.119 18118 18140 E AndroidRuntime: z@66:1913
10-13 19:34:53.119 18118 18140 E AndroidRuntime: j@66:2675
10-13 19:34:53.119 18118 18140 E AndroidRuntime: D@66:2487
10-13 19:34:53.119 18118 18140 E AndroidRuntime: <unknown>@66:14047
10-13 19:34:53.119 18118 18140 E AndroidRuntime: Ie@66:70003
10-13 19:34:53.119 18118 18140 E AndroidRuntime: Me@66:13717
10-13 19:34:53.119 18118 18140 E AndroidRuntime: De@66:13890
10-13 19:34:53.119 18118 18140 E AndroidRuntime: receiveEvent@66:14327
10-13 19:34:53.119 18118 18140 E AndroidRuntime: value@18:3369
10-13 19:34:53.119 18118 18140 E AndroidRuntime: <unknown>@18:851
10-13 19:34:53.119 18118 18140 E AndroidRuntime: value@18:2613
10-13 19:34:53.119 18118 18140 E AndroidRuntime: value@18:823
10-13 19:34:53.119 18118 18140 E AndroidRuntime:
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
10-13 19:34:53.119 18118 18140 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
10-13 19:34:53.121   960  2810 W ActivityManager:   Force finishing activity de.elumion.lacucaracha6/.MainActivity
```

Any ideas?

Thanks and Kind regards

**Comment by tsapeta** [comment]
Hey @Keyj1n,
`*.so` files are already prebuilt for `armeabi-v7a` and `x86` architectures and are provided by `expo-gl-cpp` dependency. See here: https://github.com/expo/expo-gl-cpp/tree/master/android/dist/armeabi-v7a
You app should be able to automatically detect these binaries and use them, but looks like it's not happening in your case.
What is the version of `soloader` you're using?

**Comment by sjchmiela** [comment]
Also one could read:

```
10-13 19:34:53.119 18118 18140 E AndroidRuntime: com.facebook.react.common.JavascriptException: Unexpected token ';'. Expected a parameter pattern or a ')' in parameter list., stack:
```

which suggests some JS code problem. 🙂

**Comment by Chrisigrimm** [comment]
Hey @tsapeta ,

thanks for the answer. I could solve the problem by clean the project and rebuild everything.

Thanks
